#!/bin/bash

#Ok, we are calling python to each csv file in each patient's folder.
#Python will then take each csv file and append it to a master csv list.
#Requirements: This script needs to be in the same directory as the python scripts
#Note: Paths can be easily added or removed. 

#Process each csv file
for file in /home/phil/hr4e/data/patient_data/hr4e_patient.xml
do
	echo "\n Running Python on $file..."
	python csvcleanup.py $file   
done


#All done! Go figure.
echo "all done"

